In [300]:
import re
text = "This class is about DataScience."
re.search("class",text)

In [301]:
text2 = "This class is about DataScience.there are 30 people in the class."
re.search("class",text2)

In [302]:
re.match("This",text2)

In [303]:
text3 = "the cat sat on the mat and saw another cat"
re.findall("cat",text3)

['cat', 'cat']

In [304]:
text4 = "I completed my graduation in 2025."
re.findall("[0-9]",text4)

['2', '0', '2', '5']

In [305]:
re.sub(r"\d+","the year of 2025",text4)

'I completed my graduation in the year of 2025.'

In [306]:
text5 = "My mobile number is 9876543210."
re.sub("\d{10}","****",text5)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_3261/263699515.py:2: SyntaxWarning: invalid escape sequence '\d'
  re.sub("\d{10}","****",text5)

'My mobile number is ****.'

In [307]:
string1 = "This is my mobile number 9876543210 and Pan number:QWERT1234Y."
re.findall(r"[A-Z]{5}[0-9]{4}[A-Z]",string1)

['QWERT1234Y']

In [308]:
string1 = "This is my mobile number 9876543210 and Pan number:QWERT1234Y. This is my email id edukron.banglore@gmail.com"
re.findall(r"[a-z.]+@[a-z]{5}.[a-z]{3}",string1)

['edukron.banglore@gmail.com']

In [309]:
text6 = "for any queries pls contact on edukron_123@gmail.com"

In [310]:
re.findall(r"[a-z0-9._]+[a-z0-9._]+?@[a-z]{5}.[a-z]{3}",text5)

[]

In [311]:
assignemnt_text = """On 04/04/2025, Ms. Anjali Verma received a credit of ₹1,20,000 in her HDFC account (A/C No: 50100233456789) via NEFT (UTR No: HDFCNEFT0425TXN00123).
The amount was transferred from XYZ Pvt Ltd (GSTIN: 27AAACX1234B1Z9), as part of her consultancy payment. Her PAN number is APLPV2345C.
Anjali made an online purchase worth ₹8,499 on Myntra (Order ID: MYN/ORD/20250403/1147) and paid ₹2,300 for utilities through Google Pay
(Txn ID: GPay2025040312345). For inquiries, she can be contacted at +91-9988776655 or emailed at anjali.verma84@gmail.com.
Her office contact number is 080-23456789. The company also sent an invoice (Invoice No: INV/2025/XYZ-004) dated 03/04/2025.
She logged into the company portal using her ID: EMP-2025-0098."""

In [312]:
re.findall(r"\d{2}/\d{2}/\d{4}",assignemnt_text)

['04/04/2025', '03/04/2025']

In [313]:
re.findall(r"₹[\d,]+(?:\.\d{2})?",assignemnt_text)

['₹1,20,000', '₹8,499', '₹2,300']

In [314]:
re.findall(r"A/C No: \d{14}",assignemnt_text)

['A/C No: 50100233456789']

In [315]:
re.findall(r"[0-9]{2}[A-Z]{5}[0-9]{4}[A-z][0-9][A-Z][0-9]",assignemnt_text)

['27AAACX1234B1Z9']

In [316]:
re.findall(r"[A-Z]{5}[0-9]{4}[A-Z]",assignemnt_text)

['CNEFT0425T', 'AAACX1234B', 'APLPV2345C']

In [317]:
re.findall(r"[a-z.0-9]+@[a-z]{5}.com",assignemnt_text)

['anjali.verma84@gmail.com']

In [318]:
string1="dinesh.123@gmail.com"

In [319]:
re.findall(r"[a-z]{6}.[0-9]{3}@[a-z]{5}.[a-z]{3}",string1)

['dinesh.123@gmail.com']

In [320]:
import pandas as pd
import numpy as np
import string
import nltk,re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')
stop_words=set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [321]:
df=pd.read_excel("/content/reviews_sampledata (1).xlsx")

In [322]:
df

,Label,Title,Review
0,2,Stuning even for the non-gamer,This sound track was beautiful! It paints the ...
1,2,The best soundtrack ever to anything.,I'm reading a lot of reviews saying that this ...
2,2,Amazing!,This soundtrack is my favorite music of all ti...
3,2,Excellent Soundtrack,I truly like this soundtrack and I enjoy video...
4,2,"Remember, Pull Your Jaw Off The Floor After He...","If you've played the game, you know how divine..."
...,...,...,...
215,1,4 year old BORED with this after 2 weeks,I bought this for my 4 year old's birthday. Wh...
216,1,Barbie's Boring Ice Show,I bought this game because I am a figure skati...
217,1,WHAT A WASTE OF MONEY! BARBIE HAS SUNK TO NEW ...,This is the WORST CD-ROM game I have ever seen...
218,2,IT'S GREAT!,All the other reviews say this product is bori...
219,2,A good game to buy.,I bought this game for my daughter who is almo...

In [323]:
df.head()

,Label,Title,Review
0,2,Stuning even for the non-gamer,This sound track was beautiful! It paints the ...
1,2,The best soundtrack ever to anything.,I'm reading a lot of reviews saying that this ...
2,2,Amazing!,This soundtrack is my favorite music of all ti...
3,2,Excellent Soundtrack,I truly like this soundtrack and I enjoy video...
4,2,"Remember, Pull Your Jaw Off The Floor After He...","If you've played the game, you know how divine..."

In [324]:
df.columns

Index(['Label', 'Title', 'Review'], dtype='object')

In [325]:
df['Label'].value_counts()

Label
2    118
1    102
Name: count, dtype: int64

In [326]:
df.drop(columns=['Title'],inplace=True)

In [327]:
df['lowercase']=df['Review'].str.lower()

In [268]:
df['lowercase']

0      this sound track was beautiful! it paints the ...
1      i'm reading a lot of reviews saying that this ...
2      this soundtrack is my favorite music of all ti...
3      i truly like this soundtrack and i enjoy video...
4      if you've played the game, you know how divine...
                             ...
215    i bought this for my 4 year old's birthday. wh...
216    i bought this game because i am a figure skati...
217    this is the worst cd-rom game i have ever seen...
218    all the other reviews say this product is bori...
219    i bought this game for my daughter who is almo...
Name: lowercase, Length: 220, dtype: object

In [328]:
df['punct_removed']=df['lowercase'].apply(lambda x:''.join([char for char in x if char not in string.punctuation]))

In [270]:
df['punct_removed']

0      this sound track was beautiful it paints the s...
1      im reading a lot of reviews saying that this i...
2      this soundtrack is my favorite music of all ti...
3      i truly like this soundtrack and i enjoy video...
4      if youve played the game you know how divine t...
                             ...
215    i bought this for my 4 year olds birthday whil...
216    i bought this game because i am a figure skati...
217    this is the worst cdrom game i have ever seen ...
218    all the other reviews say this product is bori...
219    i bought this game for my daughter who is almo...
Name: punct_removed, Length: 220, dtype: object

In [329]:
df['num_removed']=df['punct_removed'].apply(lambda x:''.join([char for char in x if not char.isdigit()]))

In [272]:
df['num_removed']

0      this sound track was beautiful it paints the s...
1      im reading a lot of reviews saying that this i...
2      this soundtrack is my favorite music of all ti...
3      i truly like this soundtrack and i enjoy video...
4      if youve played the game you know how divine t...
                             ...
215    i bought this for my  year olds birthday while...
216    i bought this game because i am a figure skati...
217    this is the worst cdrom game i have ever seen ...
218    all the other reviews say this product is bori...
219    i bought this game for my daughter who is almo...
Name: num_removed, Length: 220, dtype: object

In [330]:
pattern="This class is about datascience"
re.search("about",pattern)

In [331]:
re.match("This",pattern)

In [332]:
re.match("class",pattern)

In [333]:
re.match("This",text2)

In [334]:
re.match("is",pattern)

In [335]:
pattern1="the cat sat on the cat and the mat and saw another cat"
re.findall("cat",pattern1)

['cat', 'cat', 'cat']

In [279]:
text4="I completed my graduation in 2025"
re.findall("[0-9]",text4)

['2', '0', '2', '5']

In [280]:
re.findall("[A-Z]",text4)

['I']

In [281]:
re.findall("[a-z]",text4)

['c',
 'o',
 'm',
 'p',
 'l',
 'e',
 't',
 'e',
 'd',
 'm',
 'y',
 'g',
 'r',
 'a',
 'd',
 'u',
 'a',
 't',
 'i',
 'o',
 'n',
 'i',
 'n']

In [282]:
re.findall("[aeiou]",text4)

['o', 'e', 'e', 'a', 'u', 'a', 'i', 'o', 'i']

In [283]:
text4

'I completed my graduation in 2025'

In [284]:
re.sub(r"\d+","the year of 2025",text4)

'I completed my graduation in the year of 2025'

In [285]:
text5="My mobile number is 9876543210"
re.sub(r"\d+","*****",text5 )

'My mobile number is *****'

In [286]:
re.sub(r"\d{10}","*****",text5)

'My mobile number is *****'

In [287]:
string1="This is my mobile nuber 9876543210 and pan number:LITPK7695D. This is my email id edukron.bangalore@gmail.com"
re.findall(r"[a-z.]+@[a-z]{5}.[a-z]{3}",string1)

['edukron.bangalore@gmail.com']

In [288]:
re.findall(r"[A-Z]{5}[0-9]{4}[A-Z]{1}",string1)

['LITPK7695D']

In [289]:
assignemnt_text = """On 04/04/2025, Ms. Anjali Verma received a credit of ₹1,20,000 in her HDFC account (A/C No: 50100233456789) via NEFT (UTR No: HDFCNEFT0425TXN00123).
The amount was transferred from XYZ Pvt Ltd (GSTIN: 27AAACX1234B1Z9), as part of her consultancy payment. Her PAN number is APLPV2345C.
Anjali made an online purchase worth ₹8,499 on Myntra (Order ID: MYN/ORD/20250403/1147) and paid ₹2,300 for utilities through Google Pay
(Txn ID: GPay2025040312345). For inquiries, she can be contacted at +91-9988776655 or emailed at anjali.verma84@gmail.com.
Her office contact number is 080-23456789. The company also sent an invoice (Invoice No: INV/2025/XYZ-004) dated 03/04/2025.
She logged into the company portal using her ID: EMP-2025-0098."""

In [290]:
re.findall(r"\d{2}/\d{2}/\d{4}",assignemnt_text)

['04/04/2025', '03/04/2025']

In [291]:
re.findall(r"A/C No: \d{14}",assignemnt_text)

['A/C No: 50100233456789']

In [292]:
re.findall(r"[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[0-9]{1}[A-Z]{1}[0-9]{1}",assignemnt_text)

['27AAACX1234B1Z9']

In [293]:
string2="dinesh.123@gmail.com"
re.findall(r"[a-z]{6}.[0-9]{3}@[a-z]{5}.[a-z]{3}",string2)

['dinesh.123@gmail.com']

In [294]:
string3="mounishareddy.k2003@gmail.com"
re.findall(r"[a-z]{13}.[a-z]{1}[0-9]{4}@[a-z]{5}.[a-z]{3}",string3)

['mounishareddy.k2003@gmail.com']

In [295]:
df.head()

,Label,Review,lowercase,punct_removed,num_removed
0,2,This sound track was beautiful! It paints the ...,this sound track was beautiful! it paints the ...,this sound track was beautiful it paints the s...,this sound track was beautiful it paints the s...
1,2,I'm reading a lot of reviews saying that this ...,i'm reading a lot of reviews saying that this ...,im reading a lot of reviews saying that this i...,im reading a lot of reviews saying that this i...
2,2,This soundtrack is my favorite music of all ti...,this soundtrack is my favorite music of all ti...,this soundtrack is my favorite music of all ti...,this soundtrack is my favorite music of all ti...
3,2,I truly like this soundtrack and I enjoy video...,i truly like this soundtrack and i enjoy video...,i truly like this soundtrack and i enjoy video...,i truly like this soundtrack and i enjoy video...
4,2,"If you've played the game, you know how divine...","if you've played the game, you know how divine...",if youve played the game you know how divine t...,if youve played the game you know how divine t...

In [296]:
df['Label'].value_counts()

Label
2    118
1    102
Name: count, dtype: int64

In [297]:
df.columns

Index(['Label', 'Review', 'lowercase', 'punct_removed', 'num_removed'], dtype='object')

In [298]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return ' '.join(filtered_tokens)

In [340]:
df['stopwords_removed'] = df['num_removed'].apply(remove_stopwords)

In [341]:
def remove_url(text):
  return re.sub(r'http\S+|www.\S+','',text)
df['url_removed']=df['stopwords_removed'].apply(remove_url)

In [342]:
def remove_hashtag(text):
  return re.sub(r'#\w+','',text)
df['hashtag_removed']=df['url_removed'].apply(remove_hashtag)

In [343]:
def remove_emojis(text):
  emoticon_pattern=r"[:;=]-?[)(|DPOo0/\\]+"
  text=re.sub(emoticon_pattern,'',text)
  return text
df['emoji_removed']=df['hashtag_removed'].apply(remove_emojis)

In [344]:
def remove_extra_whitespaces(text):
  return ' '.join(text.split())
df['extra_space_removed']=df['emoji_removed'].apply(remove_extra_whitespaces)

In [345]:
df.head(2)

,Label,Review,lowercase,punct_removed,num_removed,stopwords_removed,url_removed,hashtag_removed,emoji_removed,extra_space_removed
0,2,This sound track was beautiful! It paints the ...,this sound track was beautiful! it paints the ...,this sound track was beautiful it paints the s...,this sound track was beautiful it paints the s...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...
1,2,I'm reading a lot of reviews saying that this ...,i'm reading a lot of reviews saying that this ...,im reading a lot of reviews saying that this i...,im reading a lot of reviews saying that this i...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...

In [352]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [347]:
words=["playing","played","running","crying","caring"]

In [353]:
def stemming_text(text):
  tokens=nltk.word_tokenize(text)
  stemmed_words=[ps.stem(word) for word in tokens]
  return ' '.join(stemmed_words)
#df["stemmed_words"]=df['extra_space_removed'].apply(stemming_text)

In [354]:
df["stemmed_words"]=df['extra_space_removed'].apply(stemming_text)

In [355]:
df.head(2)

,Label,Review,lowercase,punct_removed,num_removed,stopwords_removed,url_removed,hashtag_removed,emoji_removed,extra_space_removed,stemmed_words
0,2,This sound track was beautiful! It paints the ...,this sound track was beautiful! it paints the ...,this sound track was beautiful it paints the s...,this sound track was beautiful it paints the s...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beauti paint seneri mind well woul...
1,2,I'm reading a lot of reviews saying that this ...,i'm reading a lot of reviews saying that this ...,im reading a lot of reviews saying that this i...,im reading a lot of reviews saying that this i...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im read lot review say best game soundtrack fi...

In [356]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('wordnet')
lemma=WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...

In [357]:
def lemmatize_text(text):
  tokens=nltk.word_tokenize(text)
  lemma_words=[lemma.lemmatize(word,wordnet.VERB) for word in tokens]
  return ' '.join(lemma_words)

In [358]:
df['lemma_words']=df['extra_space_removed'].apply(lemmatize_text)

In [359]:
df.head(2)

,Label,Review,lowercase,punct_removed,num_removed,stopwords_removed,url_removed,hashtag_removed,emoji_removed,extra_space_removed,stemmed_words,lemma_words
0,2,This sound track was beautiful! It paints the ...,this sound track was beautiful! it paints the ...,this sound track was beautiful it paints the s...,this sound track was beautiful it paints the s...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beauti paint seneri mind well woul...,sound track beautiful paint senery mind well w...
1,2,I'm reading a lot of reviews saying that this ...,i'm reading a lot of reviews saying that this ...,im reading a lot of reviews saying that this i...,im reading a lot of reviews saying that this i...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im read lot review say best game soundtrack fi...,im read lot review say best game soundtrack fi...

In [360]:
corpus=["I love DataScience,datascience is interesting","learning DataScience is fun","I am working as a DataScientist","I Love DataScience, learning datascience is fun"]
cleaned_sentences=[i.lower() for i in corpus]

In [362]:
corpus

['I love DataScience,datascience is interesting',
 'learning DataScience is fun',
 'I am working as a DataScientist',
 'I Love DataScience, learning datascience is fun']

In [361]:
cleaned_sentences

['i love datascience,datascience is interesting',
 'learning datascience is fun',
 'i am working as a datascientist',
 'i love datascience, learning datascience is fun']

In [363]:
cleaned_text=[remove_stopwords(i) for i in cleaned_sentences]

In [364]:
cleaned_text

['love datascience , datascience interesting',
 'learning datascience fun',
 'working datascientist',
 'love datascience , learning datascience fun']

In [365]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=False)

In [366]:
cv

CountVectorizer()

In [367]:
X=cv.fit_transform(cleaned_text)

In [368]:
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (4, 7)>

In [370]:
X.toarray()

array([[2, 0, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 1],
       [2, 0, 1, 0, 1, 1, 0]])

In [371]:
cv.get_feature_names_out()

array(['datascience', 'datascientist', 'fun', 'interesting', 'learning',
       'love', 'working'], dtype=object)

In [373]:
cv.vocabulary_

{'love': 5,
 'datascience': 0,
 'interesting': 3,
 'learning': 4,
 'fun': 2,
 'working': 6,
 'datascientist': 1}

In [376]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf_X=tfidf.fit_transform(cleaned_text)

In [375]:
tfidf

TfidfVectorizer()

In [377]:
tfidf_X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 12 stored elements and shape (4, 7)>

In [378]:
tfidf_X.toarray()

array([[0.7079815 , 0.        , 0.        , 0.55459491, 0.        ,
        0.437249  , 0.        ],
       [0.49681612, 0.        , 0.61366674, 0.        , 0.61366674,
        0.        , 0.        ],
       [0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.70710678],
       [0.6829022 , 0.        , 0.42176004, 0.        , 0.42176004,
        0.42176004, 0.        ]])

In [379]:
df.head(2)

,Label,Review,lowercase,punct_removed,num_removed,stopwords_removed,url_removed,hashtag_removed,emoji_removed,extra_space_removed,stemmed_words,lemma_words
0,2,This sound track was beautiful! It paints the ...,this sound track was beautiful! it paints the ...,this sound track was beautiful it paints the s...,this sound track was beautiful it paints the s...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beauti paint seneri mind well woul...,sound track beautiful paint senery mind well w...
1,2,I'm reading a lot of reviews saying that this ...,i'm reading a lot of reviews saying that this ...,im reading a lot of reviews saying that this i...,im reading a lot of reviews saying that this i...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im read lot review say best game soundtrack fi...,im read lot review say best game soundtrack fi...

In [381]:
def tokenize_text(text):
  return word_tokenize(text)
df['tokens']=df['lemma_words'].apply(tokenize_text)

In [382]:
df.head(2)

,Label,Review,lowercase,punct_removed,num_removed,stopwords_removed,url_removed,hashtag_removed,emoji_removed,extra_space_removed,stemmed_words,lemma_words,tokens
0,2,This sound track was beautiful! It paints the ...,this sound track was beautiful! it paints the ...,this sound track was beautiful it paints the s...,this sound track was beautiful it paints the s...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beauti paint seneri mind well woul...,sound track beautiful paint senery mind well w...,"[sound, track, beautiful, paint, senery, mind,..."
1,2,I'm reading a lot of reviews saying that this ...,i'm reading a lot of reviews saying that this ...,im reading a lot of reviews saying that this i...,im reading a lot of reviews saying that this i...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im read lot review say best game soundtrack fi...,im read lot review say best game soundtrack fi...,"[im, read, lot, review, say, best, game, sound..."

In [384]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test=train_test_split(df['lemma_words'],df['Label'],test_size=0.1,random_state=12)

In [385]:
X_train.shape, X_test.shape,y_train.shape,y_test.shape

((198,), (22,), (198,), (22,))

In [386]:
df.head()

,Label,Review,lowercase,punct_removed,num_removed,stopwords_removed,url_removed,hashtag_removed,emoji_removed,extra_space_removed,stemmed_words,lemma_words,tokens
0,2,This sound track was beautiful! It paints the ...,this sound track was beautiful! it paints the ...,this sound track was beautiful it paints the s...,this sound track was beautiful it paints the s...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beautiful paints senery mind well ...,sound track beauti paint seneri mind well woul...,sound track beautiful paint senery mind well w...,"[sound, track, beautiful, paint, senery, mind,..."
1,2,I'm reading a lot of reviews saying that this ...,i'm reading a lot of reviews saying that this ...,im reading a lot of reviews saying that this i...,im reading a lot of reviews saying that this i...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im reading lot reviews saying best game soundt...,im read lot review say best game soundtrack fi...,im read lot review say best game soundtrack fi...,"[im, read, lot, review, say, best, game, sound..."
2,2,This soundtrack is my favorite music of all ti...,this soundtrack is my favorite music of all ti...,this soundtrack is my favorite music of all ti...,this soundtrack is my favorite music of all ti...,soundtrack favorite music time hands intense s...,soundtrack favorite music time hands intense s...,soundtrack favorite music time hands intense s...,soundtrack favorite music time hands intense s...,soundtrack favorite music time hands intense s...,soundtrack favorit music time hand intens sad ...,soundtrack favorite music time hand intense sa...,"[soundtrack, favorite, music, time, hand, inte..."
3,2,I truly like this soundtrack and I enjoy video...,i truly like this soundtrack and i enjoy video...,i truly like this soundtrack and i enjoy video...,i truly like this soundtrack and i enjoy video...,truly like soundtrack enjoy video game music p...,truly like soundtrack enjoy video game music p...,truly like soundtrack enjoy video game music p...,truly like soundtrack enjoy video game music p...,truly like soundtrack enjoy video game music p...,truli like soundtrack enjoy video game music p...,truly like soundtrack enjoy video game music p...,"[truly, like, soundtrack, enjoy, video, game, ..."
4,2,"If you've played the game, you know how divine...","if you've played the game, you know how divine...",if youve played the game you know how divine t...,if youve played the game you know how divine t...,youve played game know divine music every sing...,youve played game know divine music every sing...,youve played game know divine music every sing...,youve played game know divine music every sing...,youve played game know divine music every sing...,youv play game know divin music everi singl so...,youve play game know divine music every single...,"[youve, play, game, know, divine, music, every..."

In [388]:
cv=CountVectorizer(ngram_range=(1,2))
Xtrain_cv=cv.fit_transform(X_train)
Xtest_cv=cv.transform(X_test)

In [389]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=100)
lr.fit(Xtrain_cv,y_train)
y_pred = lr.predict(Xtest_cv)

In [390]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [391]:
print("Accuracy_Score is:", accuracy_score(y_test,y_pred))
print("precision_score is:", precision_score(y_test,y_pred))
print("recall_score is:", recall_score(y_test,y_pred))
print("f1_score is:", f1_score(y_test,y_pred))

Accuracy_Score is: 0.6818181818181818
precision_score is: 0.5555555555555556
recall_score is: 0.625
f1_score is: 0.5882352941176471

In [392]:
print("Accuracy_Score is:", accuracy_score(y_test,y_pred))
print("precision_score is:", precision_score(y_test,y_pred))
print("recall_score is:", recall_score(y_test,y_pred))
print("f1_score is:", f1_score(y_test,y_pred))

Accuracy_Score is: 0.6818181818181818
precision_score is: 0.5555555555555556
recall_score is: 0.625
f1_score is: 0.5882352941176471

In [394]:
cleaned_text

['love datascience , datascience interesting',
 'learning datascience fun',
 'working datascientist',
 'love datascience , learning datascience fun']

In [395]:
from nltk.util import ngrams
n=2

for sentence in cleaned_text:
    words = sentence.split()
    result = list(ngrams(words,n))
    print(result)

[('love', 'datascience'), ('datascience', ','), (',', 'datascience'), ('datascience', 'interesting')]
[('learning', 'datascience'), ('datascience', 'fun')]
[('working', 'datascientist')]
[('love', 'datascience'), ('datascience', ','), (',', 'learning'), ('learning', 'datascience'), ('datascience', 'fun')]

In [396]:
tfidf_v = TfidfVectorizer()
Xtrain_tfidf = tfidf_v.fit_transform(X_train)
Xtest_tfidf = tfidf_v.transform(X_test)

In [397]:
lr = LogisticRegression(max_iter=100)
lr.fit(Xtrain_tfidf,y_train)
y_pred_tfidf = lr.predict(Xtest_tfidf)

In [398]:
print("Accuracy_Score is:", accuracy_score(y_test,y_pred_tfidf))
print("precision_score is:", precision_score(y_test,y_pred_tfidf))
print("recall_score is:", recall_score(y_test,y_pred_tfidf))
print("f1_score is:", f1_score(y_test,y_pred_tfidf))

Accuracy_Score is: 0.6363636363636364
precision_score is: 0.5
recall_score is: 0.5
f1_score is: 0.5